# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  db:
    build:
      context: .
      dockerfile: ./Dockerfile-db
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=yourStrong(!)Password
    volumes:
      - /var/opt/mssql
  api:
    build:
      context: .
      dockerfile: ./Dockerfile-api
    ports:
      - 5151:5151
    depends_on:
      - db
  
    